### PR TITLE
Image classification notebooks

### LINKED ISSUE #1: Create tutorial notebooks for image classification
- [x] HRNet Notebook
- [x] Fastai 2 Notebook

### PR DESCRIPTION
**Pull request by Andrevmatias**
closes #1

### CODE REVIEW

**Review by johnnv1 — CHANGES_REQUESTED** [review]
The CI still failing because of a disagreement between isort and black. 

To fix this, just import one module / function by line:

```python
from fastai.vision.all import F1Score
from fastai.vision.all import ImageDataLoaders
from fastai.vision.all import Normalize
from fastai.vision.all import PILImage
# ...
```

I will also see a manner to auto-fix this

Other thing, needs to add `albumentations` at the `requeriments-dev` (also in #7)

**Comment by ThiagoZLC** [comment]
### Resnet

I fixed the problem the importing problem from the resnet notebook by changing:
````
from fastai.vision.all import (
    F1Score,
    ImageDataLoaders,
    Normalize,
    PILImage,
    Precision,
    Recall,
    SaveModelCallback,
    ShowGraphCallback,
    Transform,
    accuracy,
    get_image_files,
    get_learner,
    imagenet_stats,
)
````
for "from fastai.vision.all import *"

**Comment by ThiagoZLC** [comment]
### Resnet

I found another problem with the Resnet notebook

There was a problem in the cell:
```
bs = 8  # Adjust the batch size accordingly to the GPU VRAM capacity

Creates the dataloader

data = ImageDataLoaders.from_df(
    images_df[~images_df["is_test"]],
    fn_col="path",
    label_col="label",
    valid_col="is_val",
    path="/",
    bs=bs,
    item_tfms=transforms,
    batch_tfms=Normalize.from_stats(*imagenet_stats),
)

````
````
KeyError Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

9 frames

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'is_val'


The above exception was the direct cause of the following exception:

KeyError Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'is_val'
````


I don't know if it's an error in how the MindFunga dataset is arranged, or a code error. The dataset is just a directory divided into train, val and test and each of the directories contains folders with species names.

**Comment by ThiagoZLC** [comment]
### HRnet

I found a problem in this Hrnet notebook cell:

Do I have to download this "models_hrnet_18_v41" from somewhere? I didn't find it in the base directory and I didn't quite understand how to proceed.

````
# Output and Logs

final_output_dir = path_models

root_output_dir = Path(cfg.OUTPUT_DIR)
if not root_output_dir.exists():
    print(f"=> creating {root_output_dir}")
    root_output_dir.mkdir()

dataset = cfg.DATASET.DATASET
model_name = "hrnet_18"

print(f"=> creating {final_output_dir}")
final_output_dir.mkdir(parents=True, exist_ok=True)

time_str = time.strftime("%Y-%m-%d-%H-%M")
log_file = "{}_{}.log".format(time_str, "train")
final_log_file = final_output_dir / log_file
head = "%(asctime)-15s %(message)s"
logging.basicConfig(filename=str(final_log_file), format=head)
logger = logging.getLogger()
logger.setLevel(logging.INFO)
console = logging.StreamHandler()
logging.getLogger("").addHandler(console)

tensorboard_log_dir = Path(cfg.LOG_DIR) / dataset / model_name / (time_str)
print(f"=> creating {tensorboard_log_dir}")
tensorboard_log_dir.mkdir(parents=True, exist_ok=True)

writer_dict = {
    "writer": SummaryWriter(log_dir=tensorboard_log_dir),
    "train_global_steps": 0,
    "valid_global_steps": 0,
}
````

`````
=> creating /content/gdrive/Shareddrives/MindFunga/Outputs/Hrnet/Models/Outputs/classification/models_hrnet_18_v41

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-15-16208a01c3bd>](https://localhost:8080/#) in <module>
      6 if not root_output_dir.exists():
      7     print(f"=> creating {root_output_dir}")
----> 8     root_output_dir.mkdir()
      9 
     10 dataset = cfg.DATASET.DATASET

[/usr/lib/python3.7/pathlib.py](https://localhost:8080/#) in mkdir(self, mode, parents, exist_ok)
   1271             self._raise_closed()
   1272         try:
-> 1273             self._accessor.mkdir(self, mode)
   1274         except FileNotFoundError:
   1275             if not parents or self.parent == self:

FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/Shareddrives/MindFunga/Outputs/Hrnet/Models/Outputs/classification/models_hrnet_18_v41'
``````

**Comment by Andrevmatias** [comment]
> ### Resnet
> 
> I found another problem with the Resnet notebook
> 
> There was a problem in the cell:
> 
> ```
> bs = 8  # Adjust the batch size accordingly to the GPU VRAM capacity
> 
> Creates the dataloader
> 
> data = ImageDataLoaders.from_df(
>     images_df[~images_df["is_test"]],
>     fn_col="path",
>     label_col="label",
>     valid_col="is_val",
>     path="/",
>     bs=bs,
>     item_tfms=transforms,
>     batch_tfms=Normalize.from_stats(*imagenet_stats),
> )
> ```
> 
> ```
> KeyError Traceback (most recent call last)
> 
> [/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
>    3360             try:
> -> 3361                 return self._engine.get_loc(casted_key)
>    3362             except KeyError as err:
> 
> 9 frames
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: 'is_val'
> 
> 
> The above exception was the direct cause of the following exception:
> 
> KeyError Traceback (most recent call last)
> 
> [/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
>    3361                 return self._engine.get_loc(casted_key)
>    3362             except KeyError as err:
> -> 3363                 raise KeyError(key) from err
>    3364
>    3365         if is_scalar(key) and isna(key) and not self.hasnans:
> 
> KeyError: 'is_val'
> ```
> 
> I don't know if it's an error in how the MindFunga dataset is arranged, or a code error. The dataset is just a directory divided into train, val and test and each of the directories contains folders with species names.

It's working using the UFSC OCPap dataset. Are your folders following the correct structure: [train|val|test]/[class]? Check the structure of the DataFrame created in the previous cell to see if it's valid.

**Comment by Andrevmatias** [comment]
> ### HRnet
> 
> I found a problem in this Hrnet notebook cell:
> 
> Do I have to download this "models_hrnet_18_v41" from somewhere? I didn't find it in the base directory and I didn't quite understand how to proceed.
> 
> ```
> # Output and Logs
> 
> final_output_dir = path_models
> 
> root_output_dir = Path(cfg.OUTPUT_DIR)
> if not root_output_dir.exists():
>     print(f"=> creating {root_output_dir}")
>     root_output_dir.mkdir()
> 
> dataset = cfg.DATASET.DATASET
> model_name = "hrnet_18"
> 
> print(f"=> creating {final_output_dir}")
> final_output_dir.mkdir(parents=True, exist_ok=True)
> 
> time_str = time.strftime("%Y-%m-%d-%H-%M")
> log_file = "{}_{}.log".format(time_str, "train")
> final_log_file = final_output_dir / log_file
> head = "%(asctime)-15s %(message)s"
> logging.basicConfig(filename=str(final_log_file), format=head)
> logger = logging.getLogger()
> logger.setLevel(logging.INFO)
> console = logging.StreamHandler()
> logging.getLogger("").addHandler(console)
> 
> tensorboard_log_dir = Path(cfg.LOG_DIR) / dataset / model_name / (time_str)
> print(f"=> creating {tensorboard_log_dir}")
> tensorboard_log_dir.mkdir(parents=True, exist_ok=True)
> 
> writer_dict = {
>     "writer": SummaryWriter(log_dir=tensorboard_log_dir),
>     "train_global_steps": 0,
>     "valid_global_steps": 0,
> }
> ```
> 
> ```
> => creating /content/gdrive/Shareddrives/MindFunga/Outputs/Hrnet/Models/Outputs/classification/models_hrnet_18_v41
> 
> ---------------------------------------------------------------------------
> 
> FileNotFoundError                         Traceback (most recent call last)
> 
> [<ipython-input-15-16208a01c3bd>](https://localhost:8080/#) in <module>
>       6 if not root_output_dir.exists():
>       7     print(f"=> creating {root_output_dir}")
> ----> 8     root_output_dir.mkdir()
>       9 
>      10 dataset = cfg.DATASET.DATASET
> 
> [/usr/lib/python3.7/pathlib.py](https://localhost:8080/#) in mkdir(self, mode, parents, exist_ok)
>    1271             self._raise_closed()
>    1272         try:
> -> 1273             self._accessor.mkdir(self, mode)
>    1274         except FileNotFoundError:
>    1275             if not parents or self.parent == self:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/Shareddrives/MindFunga/Outputs/Hrnet/Models/Outputs/classification/models_hrnet_18_v41'
> ```

This is the models output folder. It should exist before running the training. I added a line of code to create this directory and prevent this error.

**Comment by ThiagoZLC** [comment]
### HRnet

Now the Hrnet notebook breaks on this cell:

I tried to search for it on the internet but I didn't find anything sorry.

````
model = eval("models." + cfg.MODEL.NAME + ".get_cls_net")(cfg)

gpus = list(cfg.GPUS)
model = torch.nn.DataParallel(model, device_ids=gpus).cuda()
criterion = torch.nn.CrossEntropyLoss().cuda()
optimizer = get_optimizer(cfg, model)

````
Resulting this:

````

NameError                                 Traceback (most recent call last)

[<ipython-input-18-2e50c0914d3f>](https://localhost:8080/#) in <module>
----> 1 model = eval("models." + cfg.MODEL.NAME + ".get_cls_net")(cfg)
      2 
      3 gpus = list(cfg.GPUS)
      4 model = torch.nn.DataParallel(model, device_ids=gpus).cuda()
      5 criterion = torch.nn.CrossEntropyLoss().cuda()

<string> in <module>

NameError: name 'models' is not defined

**Comment by Andrevmatias** [comment]
> ### HRnet
> 
> Now the Hrnet notebook breaks on this cell:
> 
> I tried to search for it on the internet but I didn't find anything sorry.
> 
> ```
> model = eval("models." + cfg.MODEL.NAME + ".get_cls_net")(cfg)
> 
> gpus = list(cfg.GPUS)
> model = torch.nn.DataParallel(model, device_ids=gpus).cuda()
> criterion = torch.nn.CrossEntropyLoss().cuda()
> optimizer = get_optimizer(cfg, model)
> ```
> 
> Resulting this:
> 
> ```
> 
> NameError                                 Traceback (most recent call last)
> 
> [<ipython-input-18-2e50c0914d3f>](https://localhost:8080/#) in <module>
> ----> 1 model = eval("models." + cfg.MODEL.NAME + ".get_cls_net")(cfg)
>       2 
>       3 gpus = list(cfg.GPUS)
>       4 model = torch.nn.DataParallel(model, device_ids=gpus).cuda()
>       5 criterion = torch.nn.CrossEntropyLoss().cuda()
> 
> <string> in <module>
> 
> NameError: name 'models' is not defined
> ```

Are you sure that the third code cell ("Installs HRNet from the git source") ran without any errors?

**Comment by ThiagoZLC** [comment]
Yes, no errors

**Comment by ThiagoZLC** [comment]
I'm sending the notebook link, there I put pictures of how the dataset is organized, maybe it's an adaptation problem that I didn't notice.

https://drive.google.com/file/d/1XJC3G702Oc7FvSYt7O3ZXiJw3zems8AU/view?usp=sharing

**Comment by Andrevmatias** [comment]
> I'm sending the notebook link, there I put pictures of how the dataset is organized, maybe it's an adaptation problem that I didn't notice.
> 
> https://drive.google.com/file/d/1XJC3G702Oc7FvSYt7O3ZXiJw3zems8AU/view?usp=sharing

Actually, the `models` import was removed because the linter couldn't detect its use inside `eval()`. I've disabled this rule for this import, can you try again?

**Comment by ThiagoZLC** [comment]
Now that part it's fixed, but i found another one sorry kkkkkkkkkkkkk

It's on the training cell. Do you have any ideia how to solve? i'm really not familiar with this.

Same link if you want to see:
https://drive.google.com/file/d/1XJC3G702Oc7FvSYt7O3ZXiJw3zems8AU/view?usp=sharing


````
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-18-409703215128>](https://localhost:8080/#) in <module>
     13         final_output_dir,
     14         tensorboard_log_dir,
---> 15         writer_dict,
     16     )
     17     lr_scheduler.step()

8 frames

[/HRNet/lib/models/cls_hrnet.py](https://localhost:8080/#) in forward(self, x)
    240                     y = y + x[j]
    241                 else:
--> 242                     y = y + self.fuse_layers[i][j](x[j])
    243             x_fuse.append(self.relu(y))
    244 

RuntimeError: The size of tensor a (250) must match the size of tensor b (252) at non-singleton dimension 3````

**Comment by Andrevmatias** [comment]
> Now that part it's fixed, but i found another one sorry kkkkkkkkkkkkk
> 
> It's on the training cell. Do you have any ideia how to solve? i'm really not familiar with this.
> 
> Same link if you want to see: https://drive.google.com/file/d/1XJC3G702Oc7FvSYt7O3ZXiJw3zems8AU/view?usp=sharing
> 
> ```
> ---------------------------------------------------------------------------
> 
> RuntimeError                              Traceback (most recent call last)
> 
> [<ipython-input-18-409703215128>](https://localhost:8080/#) in <module>
>      13         final_output_dir,
>      14         tensorboard_log_dir,
> ---> 15         writer_dict,
>      16     )
>      17     lr_scheduler.step()
> 
> 8 frames
> 
> [/HRNet/lib/models/cls_hrnet.py](https://localhost:8080/#) in forward(self, x)
>     240                     y = y + x[j]
>     241                 else:
> --> 242                     y = y + self.fuse_layers[i][j](x[j])
>     243             x_fuse.append(self.relu(y))
>     244 
> 
> RuntimeError: The size of tensor a (250) must match the size of tensor b (252) at non-singleton dimension 3````
> ```

Are your images all 256x256 pixels? If not, you need to change the `cfg.MODEL.IMAGE_SIZE` config in the "Training configuration" cell. If they are of multiple sizes, you need to normalize them in the "Augmentations/Transforms setup" cell.

I've added this config in the Metadata section for clarity and changed the name of the transforms pipeline variable.

**Comment by ThiagoZLC** [comment]
I really forgot to change the size, but this doens't fixed the problem. Same error

**Comment by ThiagoZLC** [comment]
Maybe i'm not adapting something in my dataset? The Opap dataset is working in this notebook?

**Comment by Andrevmatias** [comment]
Yes, it's working. Try to uncomment the "Debug" cell and get more information on what is happening.

**Review by ThiagoZLC — COMMENTED** [review]
Ambos notebooks de classificação de imagem foram testados com o Dataset de Fungos do MindFunga e estão funcionais.

**Review by ThiagoZLC — APPROVED** [review]

**Pull request merged**
